spring:
#配置mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 123456
#配置redis
  data:
    redis:
      host: localhost
      port: 6379
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

